language: rust
cache: cargo
sudo: false
rust:
  - stable
  - beta
  - nightly
after_success:
  - cargo test --features=lightweight --no-default-features
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
      cargo bench --features=unstable;
    fi
